platform :ios, '10.0'
use_frameworks!

target 'Demo' do

end

target 'DemoTests' do
  pod 'Quick'
  pod 'Nimble'
  pod 'RxNimble', path: '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
